package com.lm.android.gankapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lm.android.gankapp.dao.ReadContent;
import com.lm.android.gankapp.dao.FavoriteContent;

import com.lm.android.gankapp.dao.ReadContentDao;
import com.lm.android.gankapp.dao.FavoriteContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig readContentDaoConfig;
    private final DaoConfig favoriteContentDaoConfig;

    private final ReadContentDao readContentDao;
    private final FavoriteContentDao favoriteContentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        readContentDaoConfig = daoConfigMap.get(ReadContentDao.class).clone();
        readContentDaoConfig.initIdentityScope(type);

        favoriteContentDaoConfig = daoConfigMap.get(FavoriteContentDao.class).clone();
        favoriteContentDaoConfig.initIdentityScope(type);

        readContentDao = new ReadContentDao(readContentDaoConfig, this);
        favoriteContentDao = new FavoriteContentDao(favoriteContentDaoConfig, this);

        registerDao(ReadContent.class, readContentDao);
        registerDao(FavoriteContent.class, favoriteContentDao);
    }
    
    public void clear() {
        readContentDaoConfig.getIdentityScope().clear();
        favoriteContentDaoConfig.getIdentityScope().clear();
    }

    public ReadContentDao getReadContentDao() {
        return readContentDao;
    }

    public FavoriteContentDao getFavoriteContentDao() {
        return favoriteContentDao;
    }

}
