package com.lm.android.gankapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FAVORITE_CONTENT".
 */
public class FavoriteContent {

    private Long id;
    /** Not-null value. */
    private String objectId;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String desc;
    /** Not-null value. */
    private String url;
    /** Not-null value. */
    private String who;
    /** Not-null value. */
    private String publishedAt;
    /** Not-null value. */
    private java.util.Date favoriteAt;

    public FavoriteContent() {
    }

    public FavoriteContent(Long id) {
        this.id = id;
    }

    public FavoriteContent(Long id, String objectId, String type, String desc, String url, String who, String publishedAt, java.util.Date favoriteAt) {
        this.id = id;
        this.objectId = objectId;
        this.type = type;
        this.desc = desc;
        this.url = url;
        this.who = who;
        this.publishedAt = publishedAt;
        this.favoriteAt = favoriteAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getDesc() {
        return desc;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    /** Not-null value. */
    public String getWho() {
        return who;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWho(String who) {
        this.who = who;
    }

    /** Not-null value. */
    public String getPublishedAt() {
        return publishedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPublishedAt(String publishedAt) {
        this.publishedAt = publishedAt;
    }

    /** Not-null value. */
    public java.util.Date getFavoriteAt() {
        return favoriteAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFavoriteAt(java.util.Date favoriteAt) {
        this.favoriteAt = favoriteAt;
    }

}
