package com.lm.android.gankapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "READ_CONTENT".
 */
public class ReadContent {

    private Long id;
    /** Not-null value. */
    private String objectId;

    public ReadContent() {
    }

    public ReadContent(Long id) {
        this.id = id;
    }

    public ReadContent(Long id, String objectId) {
        this.id = id;
        this.objectId = objectId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

}
